### ISSUE TITLE
May 17 Post sanchonet-respin checklist

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#1056]
SanchoNet has been reset and new release of node is available.
Release page : [cardano-node-8.11.0-sancho](https://github.com/IntersectMBO/cardano-node/releases/tag/8.11.0-sancho)

Following are the services that needs to be ready for smooth GovTool experience.

### Related services
- [x] New working release of DbSync 

### External Services
- [x] Blockfrost (required for wallets)
- [x] [Sanchonet CExplorer](https://sancho.cexplorer.io/block)
- [x] Eternl Wallet
- [x] Demos Wallet

### GovTool
- [x] Dev stack is up : https://dev-sanchonet.govtool.byron.network
- [x] Test stack is up :  https://govtool.cardanoapi.io
- [x] Staging stack is up : https://staging.govtool.byron.network
- [x] Beta stack is up : https://sanchogov.tools

### GovAction Loader
- [x] GovAction loader is up : https://governance-govtool.cardanoapi.io/

**Comment by mesudip** [comment]
We have reset test stack with  
- new `cardano-node:8.11.0-sancho` 
- old  `cardano-db-sync:sancho-4-2-1`

This setup is stable for us. Since we are using older `db-sync`, the backend doesn't break.

**Comment by Ryun1** [comment]
Blockfrost is back online 💪

**Comment by Ryun1** [comment]
demos wallet tested
- DRep registration, DRep update, vote delegation, stake key registration all working
- DRep voting does not work because of bootstrapping phase

**Comment by Ryun1** [comment]
DB-Sync docker image fix
via [sancho-4-3-0-docker](https://github.com/IntersectMBO/cardano-db-sync/pkgs/container/cardano-db-sync/218519444?tag=sancho-4-3-0-docker)

**Comment by mesudip** [comment]
Sanchonet CExplorer is also up.
