### ISSUE TITLE
Failing and Broken tests status tracking

### ISSUE THREAD

**Issue by sireto-sandip** [IntersectMBO/govtool#1118]
**Note** The test is run on [(https://p80-z78acf3c2-zded6a792-gtw.z937eb260.rustrocks.fr/)](https://preview.gov.tools/) in preview network

[Report](https://intersectmbo.github.io/govtool-test-reports/dev/govtool-frontend/3/#behaviors)

- [ ]  **[Flaky]** 2K_2. Should sort DReps (issue: #1983)
- [ ]  2N. Should show DRep information on details page (issue: #2791  #3490   )
#### Mobile only
- [ ]  2P. Should enable sharing of DRep details (issue: #2464  )
---
- [ ] 3E_2. Should reject invalid data in DRep form (issue: #3560 )
- [ ] 3M_2. Should reject invalid data in edit dRep form (issue: #3560 )
- [ ] 3Q Should not list dRep in the dRep directory when 'doNotList' is checked during registration (issue: #2791 )
---
- [x] **[Flaky]** 4H. Should verify none of the displayed governance actions have expired (PR https://github.com/IntersectMBO/govtool/pull/3722)
- [x] 4J. Should include metadata anchor in the vote transaction (issue: #1145 )
- [ ] 4P_4: Should display Data Not Verifiable message in live voting when metadata hash and URL do not match and is incorrect ga format (issue: #3184  )
---
- [ ] **[Flaky]** 5F. Should show notification of casted vote after vote ( stuck on in-progress status after 60 seconds of transaction success confirmed)
---
#### Mobile Only
- [ ] 5G. Should show warning in bad governance action proposal to the users to visit the site at their own risk, when external url is opened (issue #2555 ) 
---
### Proposal
---
- [x] 7G_1. Should create a proposal with proper info action data (issue #3716 )
- [x] 7G_2. Should create a proposal with proper treasury requests data (issue #3716 )
- [x] 7G_3. Should create a proposal with proper updates to the constitution data (issue #3716 )
- [x] 7G_4. Should create a proposal with proper motion of no confidence data (issue #3716 )
- [x]  7N. Should submit a draft proposal (issue #3716  )
- [ ] 7P. Should navigate to the edit proposal page when 'goto data edit screen' is selected if data does not match the anchor URL (issue: #3602  #2252 )
---
- [ ] 8B_2. Should sort the list of proposed governance actions. (issue https://github.com/IntersectMBO/govtool/issues/3739)
---
### Outcomes
--- 
- [ ] **[Flaky]** 9B_1. Should search outcomes proposal by title and id in disconnect state ( issue: #3112 )
- [ ] **[Flaky]** 9B_2. Should search outcomes proposal by title and id ( issue: #3112 )
- [ ] **[Flaky]** 9G. Should display correct vote counts on outcome details page (issue: #3287  #3492 )
- [ ] 9H_1A: Should display "Data Formatted Incorrectly" message in outcomes when hash is valid but incorrect metadata format in disconnect state. (issue: #3184 )
- [ ] 9H_1B: Should display "Data Formatted Incorrectly" message in outcomes when hash is valid but incorrect metadata format. (issue: #3184 )

### Budget Discussion
---
- [ ] **[Flaky]** 11M. Should display DRep tag, name and ID when a registered DRep comments on a proposal. (issue #2791  )
---

**Comment by kusssal** [comment]
Closing as superseded by [#4232](https://github.com/IntersectMBO/govtool/issues/4232). This is a stale mutable checklist containing old and already-completed items.
