### ISSUE TITLE
Disable UserSnap when API_KEY is not set

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#1470]
**When** 
  `VITE_USERSNAP_SPACE_API_KEY` is `null`,`undefined` or empty
**Then** 
`loadSpace` function should not be called.

### ToDo
- [ ] Check the env variable before calling `loadSpace` in `UsersnapProvider` class.
- [ ] When variable is set, the app works same as before.
- [ ] When the variable is not set, print console log "User Snap is not configured thus not initialized" and continue.

**Comment by jdyczka** [comment]
What's the use case for no api key? Isn't it more useful to have an error in the console instead of a regular log since it's more visible?

**Comment by mesudip** [comment]
@jdyczka 

Error log or warning, any  is good. We can have custom error message `User Snap is not configured due to missing API Key`.


The problem is that currently we have an `Uncaught Promise` error with stack-trace. 
![image](https://github.com/IntersectMBO/govtool/assets/11131298/b7c5ec53-018b-46f3-84fc-62377b3a4ed1)
