### ISSUE TITLE
SanchoNet re-spin checklist

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1578]
SanchoNet has been reset and new release of node is available.
Following are the services that needs to be ready for smooth GovTool experience.

### Related services
- [x] New working release of DbSync ([sancho-5.1.0](https://github.com/IntersectMBO/cardano-db-sync/releases/tag/sancho-5.1.0))

### External Services
- [x] Blockfrost (required for wallets)
- [ ] [Sanchonet CExplorer](https://sancho.cexplorer.io/block)
- [x] Eternl Wallet
- [x] Demos Wallet

### GovTool
- [x] Dev stack is up : https://dev-sanchonet.govtool.byron.network
- [x] Test stack is up :  https://govtool.cardanoapi.io
- [x] Staging stack is up : https://staging.govtool.byron.network
- [x] Beta stack is up : https://sanchogov.tools

### GovAction Loader
- [ ] GovAction loader is up : https://governance-govtool.cardanoapi.io/

**Comment by Ryun1** [comment]
demos ✅
(It should resync if you go; Settings > General Settings > Refresh Balance)

**Comment by MSzalowski** [comment]
Dev stack is up ([sancho-v.1.0.9](https://github.com/IntersectMBO/govtool/releases/tag/sancho-v1.0.9-dev) includes node-v9 and db-sync 5.0.1)

**Comment by MSzalowski** [comment]
Cannot register as a Direct Voter: https://github.com/IntersectMBO/govtool/issues/1591

**Comment by MSzalowski** [comment]
DB-Sync configuration that we have in GovTool is wrong causing the wrong values of protocol parameters which results in #1591.
Issue on DB-Sync to track this problem: https://github.com/IntersectMBO/cardano-db-sync/issues/1777
PR that might solve problem with providing proper configuration file: https://github.com/IntersectMBO/cardano-db-sync/pull/1785

**Comment by Ryun1** [comment]
Good to go!
