### ISSUE TITLE
🐛  Remaining Playwright Test Tracking

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#2073]
### Context

- [x] **4G:** Should display correct vote counts on the governance details page for DRep.
      - *Possible Fixes:* Verify test IDs and add a voting power check for SPOs and the Constitutional Committee.
      
- [x] **4K:** Should display correct vote counts on the governance details page for the disconnected state.
      - *Possible Fixes:* Verify test IDs and update the test to use test IDs instead of locators.

- [x] **5L:** Should restrict dRep votes to informational governance actions during the Bootstrapping phase.
      - *Possible Fixes:* Verify the protocol parameter check and intercept the protocol version accordingly for the bootstrapping test.

- [x] **6D:** Should open Sanchonet docs in a new tab when clicking `Learn More` on dashboards in the disconnected state.

- [x] **6E:** Should open Sanchonet docs in a new tab when clicking `Learn More` on dashboards in the connected state.

- [x] **6M:** Should navigate between footer links.
      - *Possible Fixes for 6D, 6E, and 6M:* Update the documentation URLs.

- [x] **2K_3.** Should sort DRep randomly

**Comment by bosko-m** [comment]
Is this done now @spannercode @kneerose ?

**Comment by kneerose** [comment]
@bosko-m , Yes it is done now . 
Here is the latest report: [govtool-frontend test report](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/151/#behaviors).

- Tests 4G and 4K failed due to issue #2085.
- Test 5L failed due to issue #1911.
- Test 2K_3 failed due to issue #2090.
- Test 6M failed due to update in test id of terms of use [PR](https://github.com/IntersectMBO/govtool/pull/2096)

**Comment by bosko-m** [comment]
Closing as per the comment above.
